### ISSUE TITLE
WIP : Employee list screen: display inactive users

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#111]
**Ticket not complete, needs further discussion**

There needs to be a way to see all inactive users. When as user is made inactive, they are still saved in the DB. Should they be still saved ?

**Comment by emab** [comment]
I think we need to properly define what an inactive user is. If they are someone who has left the company, I don't think we should store any more information than absolutely necessary, but I don't see why they should be completely removed from the DB.

I think we discussed yesterday that a staff member in the DB is taking up much less room than all the engagements anyway.

Are we going to go with the idea that all personal information is stripped from the DB when they are set as inactive? If so, we should make it look like someone is being deleted in the front end, as setting inactive suggests they can just be made active again.

If someone is made inactive and personal information is gone, we could still have a summary screen showing how many hours they worked, their engagements, their role and job title, their wage (and can do the summary calculations) without needing their data.

If we go with the approach that inactive users are basically deleted users in terms of the managers point of view, I don't think we should show them in a list in the same way since they don't really exist as staff members anymore, only a way to display data which is needed for summary.

**Comment by emab** [comment]
Closed, see #35.
