### ISSUE TITLE
Change delete functionality

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#134]
When a manager deletes an employee, the employees data in the back-end should be replaced with a dummy user data and their inactive field should be set to true.

**Acceptance criteria:**
- A delete endpoint exists which sets the above data
- Email field can be set to null in back-end via API Delete
- Use DELETE endpoint

**Comment by emab** [comment]
Going on from discussions we have had previously, I think this should be implemented by:

- When we `delete` a user, we remove all personal/identifying information.
- Set the inactive flag to `true`.
  - Assuming this will still be useful in the front-end when displaying staff members from the DB and excluding ones with no name.
- If an employee returns, they can be manually re-added and since their email was deleted there shouldn't be any conflicting information in the database. 

@tjanowsk @connorsettle are you guys happy for me to follow this approach?

**Comment by tjanowsk** [comment]
We need to decide what to do with e-mail field.
It is required, so we can't clear it, and it's unique so we can't just set it to an empty String.

**Comment by emab** [comment]
Ah yes I forgot that was the issue.

If it is no longer required in the database, but required for the front-end, could that cause issues? So an empty email field means not authorised by default?
