### ISSUE TITLE
Refactor some sections of the Create User endpoint

### ISSUE THREAD

**Issue by floyd924** [Furlough-Friends/rota-flex-101#81]
#66 was blocking other tickets so was merged into master with a couple of outstanding changes still to be made.

Some of these changes may have been made in a later PR. Check the current state of master and other pending PR's, and ensure the code has been refactored where required:

api/StaffController line 94:
There is a check for role != manager - we should instead call a `hasManagerPermissions` method

api.staffService line 37:
Refactor the check for engagement start time to be `!engagement.getStart().isBefore(startTime)`

api/dto/form/CreateStaffForm - how similar is this class to the StaffDTO class? If there is enough overlap, does it make sense to get rid of 1?

auth/authenticationUtils line 42:
There is currently a check to see if the user has 2 roles. This could be refactored to check the arrayList of roles contains 'manager', rather than just checking the length of the array = 2.

**Comment by emab** [comment]
> auth/authenticationUtils line 42:
There is currently a check to see if the user has 2 roles. This could be refactored to check the arrayList of roles contains 'manager', rather than just checking the length of the array = 2.

It's currently checking if the length of the token is even and then returning an optional of a role based on that alone for development purposes. I'll change this in a future PR when I properly integrate the backend with Auth0.

Can that be left as it is for now?

**Comment by tjanowsk** [comment]
> api/dto/form/CreateStaffForm - how similar is this class to the StaffDTO class? If there is enough overlap, does it make sense to get rid of 1?

For better or worse, I have removed form/CreateStaffForm.java as a part of feature/69 PR, its functions, including input validation, have been moved to StaffDto.java

I don't feel strongly about my other 2 comments, but I could include them in feature/69 as well?

**Comment by emab** [comment]
I've also done that in the refactor pull request @tjanowsk
