### ISSUE TITLE
Dev task - Fetch staff function shouldn't need to take in URL

### ISSUE THREAD

**Issue by QuarkNerd** [Furlough-Friends/rota-flex-101#89]
Minor thing, but I feel the fetchStaff function should have the URL without it being a parameter. As it stands, it is just a fetch+auth function

**Comment by tjanowsk** [comment]
The function definitely needs renaming, because as you pointed out it can do much more than just fetch staff (can also be used for engagements for example).
We don't want to end up in a situation where we have a bunch of functions that are identical except for the URL (fetchStaff, fetchEngagements and also addStaff and removeStaff, which return an updated staff list).

What we could do is :curry: the current function, so change from:
`const fetchStaff = (token: string, url: string): AppThunk => (`
to
`const fetchStuff = (url: string) => (token: string): AppThunk => (`
and then create a bunch of children functions:

`const fetchStaff = fetchStuff(STAFF_FETCH_URL);`

Would that be acceptable?

**Comment by floyd924** [comment]
One possible solution would be to create a generic 'apiService' class which has a 'get' method on it, which takes a url (which should be a const somewhere), and appends any headers required. This will also make it easier to append a token to every single request later on.

**Comment by floyd924** [comment]
You could still refer to 'fetchStaff' when you want to specifically fetch the staff, and call a `apiService.get()` method to which you pass a specific getStaff url, with any specific getStaff args

**Comment by QuarkNerd** [comment]
I think, Ideally the react components shouldn't see the URL.  If we had functions for each endpoint, those function job could be to know the URL and then call the actual getter that adds auth?
